apiVersion: v1
kind: Service
metadata:
  name: {{ include "agnos-proxy.fullname" . }}
  labels:
    {{- include "agnos-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agnos-proxy.selectorLabels" . | nindent 4 }}
